# Generated by Django 4.2.9 on 2024-01-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер карты')),
                ('office', models.CharField(max_length=100, verbose_name='Кабинет')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('busy', models.BooleanField(default=False, verbose_name='Занято')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
                'ordering': ['office'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True, verbose_name='Номер карты')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='teachers/%Y/%m/%d', verbose_name='Фото')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='Телефон')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('returned', models.BooleanField(default=False, verbose_name='Возвращен')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.office', verbose_name='Кабинет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'История карты',
                'verbose_name_plural': 'История карт',
                'ordering': ['office'],
            },
        ),
    ]
